-- Profiles table (linked to Auth.users)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  client_no TEXT UNIQUE,
  progress INTEGER DEFAULT 0,
  avatar_url TEXT,
  is_admin BOOLEAN DEFAULT FALSE, -- Admin kontrolü için eklendi
  last_seen TIMESTAMPTZ DEFAULT NOW(), -- Aktiflik takibi için eklendi
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Appointments table
CREATE TABLE appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id UUID REFERENCES auth.users ON DELETE CASCADE, -- Danışan ID'si eklendi
  full_name TEXT,
  email TEXT,
  type TEXT,
  date DATE NOT NULL,
  time TIME NOT NULL,
  status TEXT DEFAULT 'Gelecek',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS appointments_client_id_idx ON appointments(client_id);

-- Messages table
CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id UUID DEFAULT auth.uid(),
  receiver_id UUID NOT NULL, -- Mesajın kime gittiği
  text TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE, -- Okundu bilgisi
  created_at TIMESTAMPTZ DEFAULT NOW(),
  sender_role TEXT CHECK (sender_role IN ('Specialist', 'User'))
);

-- Documents table (Admin'in yüklediği dosyalar)
CREATE TABLE documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id UUID REFERENCES auth.users ON DELETE CASCADE,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  size TEXT,
  type TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Notes table
CREATE TABLE session_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id UUID REFERENCES auth.users ON DELETE CASCADE,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Test Results table
CREATE TABLE test_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id UUID REFERENCES auth.users ON DELETE SET NULL,
  test_name TEXT DEFAULT 'Kaygı ve Stres Ölçeği',
  score INTEGER NOT NULL,
  result_label TEXT NOT NULL,
  answers INTEGER[] NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Blog Posts table
CREATE TABLE blog_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  excerpt TEXT,
  content TEXT NOT NULL,
  image_url TEXT,
  category TEXT DEFAULT 'Genel',
  is_published BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Services table
CREATE TABLE services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL(10,2),
  duration INTEGER, -- Dakika cinsinden
  type TEXT DEFAULT 'Online Seans',
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Site Configuration table
CREATE TABLE site_config (
  id TEXT PRIMARY KEY, -- 'global' gibi tek bir ID kullanılacak
  site_title TEXT NOT NULL,
  site_description TEXT,
  contact_email TEXT,
  contact_phone TEXT,
  address TEXT,
  logo_url TEXT,
  colors JSONB DEFAULT '{"primary": "#7C9070", "secondary": "#F97B22"}'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert initial empty config if not exists
INSERT INTO site_config (id, site_title, site_description)
VALUES ('global', 'İçsel Sığınak', 'Profesyonel Psikolojik Danışmanlık ve Terapi')
ON CONFLICT (id) DO NOTHING;

-- Enable Realtime for Messages and Profiles
ALTER PUBLICATION supabase_realtime ADD TABLE messages;
ALTER TABLE public.profiles REPLICA IDENTITY FULL;
ALTER PUBLICATION supabase_realtime ADD TABLE profiles;

-- 8. GÜVENLİK VE ŞEMA ONARIMI (client_id Hatası İçin)
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='appointments' AND column_name='client_id') THEN
        ALTER TABLE public.appointments ADD COLUMN client_id UUID;
    END IF;
END $$;

-- 9. GERÇEK ZAMANLI KONUM TAKİBİ
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS last_known_city TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS last_seen TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());

-- Hızlı sorgu için index
CREATE INDEX IF NOT EXISTS profiles_last_seen_idx ON public.profiles (last_seen);
CREATE INDEX IF NOT EXISTS profiles_last_known_city_idx ON public.profiles (last_known_city);

-- Trigger to create a profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, is_admin)
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'full_name',
    COALESCE((new.raw_user_meta_data->>'is_admin')::boolean, false)
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
